name: Build Image

on:
  release:
    types: [published]
  push:

jobs:
  build-and-deploy:
    name: Build and deploy
    uses: chukysoria/workflows/.github/workflows/build-image.yml@10aca50bfa04d7a7cea89245556132ebc517a598 # v1.1.35
