name: 'Release Drafter'

on:
  push:
    branches:
      - main
      - master

jobs:
  update_release_draft:
    name: Release
    uses: chukysoria/workflows/.github/workflows/new-release.yml@10aca50bfa04d7a7cea89245556132ebc517a598 # v1.1.35
