name: Permission check
on:
  pull_request_target:
    paths:
      - '**/run'
      - '**/finish'
      - '**/check'
jobs:
  permission_check:
    uses: chukysoria/workflows/.github/workflows/init-svc-executable-permissions.yml@10aca50bfa04d7a7cea89245556132ebc517a598 # v1.1.35
