## STATIC CONFIG (restart traefik to update)
# enable ping to allow healthcheck on default port
ping: {}

# ---CHANGES BELOW THIS LINE---
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# log default to INFO
log:
  level: INFO

# Publish API insecure
api:
  insecure: true
  dashboard: true

# File provider
providers:
  file:
    directory: /config
    watch: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    http:
      tls:
        options: modern@file
